function varargout = toolboxContents()
% toolboxContents Overview of MATLAB NFL Analytics Toolbox assets.
%   Displayed information is used by MATLAB Add-On Explorer and the
%   "doc" command to highlight key entry points.
%
% FUNCTIONS
%   checkNFLDataPySetup - Verify Python integration and nfl_data_py availability.
%   getWeeklyStats      - Retrieve weekly player statistics as tables.
%   getPlayByPlay       - Import play-by-play data with optional filters.
%   plotTopPlayers      - Visualise top performers by statistic, week, and season.
%   showTeamDashboard   - Launch interactive dashboard for team analytics.
%
% LIVE SCRIPTS
%   doc/GettingStarted.mlx         - Guided setup walkthrough (placeholder).
%   examples/weeklyTopQuarterbacks.mlx - Example analysis workflow (placeholder).

if nargout > 0
    varargout{1} = { ...
        'FUNCTIONS'; ...
        '  checkNFLDataPySetup - Verify Python integration and nfl_data_py availability.'; ...
        '  getWeeklyStats      - Retrieve weekly player statistics as tables.'; ...
        '  getPlayByPlay       - Import play-by-play data with optional filters.'; ...
        '  plotTopPlayers      - Visualise top performers by statistic, week, and season.'; ...
        '  showTeamDashboard   - Launch interactive dashboard for team analytics.'; ...
        ''; ...
        'LIVE SCRIPTS'; ...
        '  doc/GettingStarted.mlx             - Guided setup walkthrough (placeholder).'; ...
        '  examples/weeklyTopQuarterbacks.mlx - Example analysis workflow (placeholder).'; ...
        };
end

end
